
services:
  postgres:
    image: postgres:15
    container_name: jugtours-postgres
    environment:
      POSTGRES_DB: jugtours_dev
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - jugtours-network

  backend:
    build: .
    container_name: jugtours-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DATABASE_URL=jdbc:postgresql://postgres:5432/jugtours_dev
      - DATABASE_USERNAME=${DB_USER}
      - DATABASE_PASSWORD=${DB_PASS}
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
      - AUTH0_ISSUER_URI=${AUTH0_ISSUER_URI}
      - AUTH0_REDIRECT_URI=${AUTH0_REDIRECT_URI}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - jugtours-network

volumes:
  postgres_data:

networks:
  jugtours-network:
    driver: bridge 